### ISSUE TITLE
**С чего начать проект**

### ISSUE THREAD

**Issue by GrishinAnton** [GrishinAnton/english-cards#2]
- [x] С чего начинать разработку проекта
- [x] Что стоит учесть и зафиксировать, чтобы проект был точно реализован

Я набросал две задачи во вкладке Projects.
1. Написать более детальный план
2. Технические требования.

Что еще стоит учесть на старте проекта?  На что обратить внимание?

**Comment by vitkarpov** [comment]
Начать стоит с дизайн-документа. Не упарываясь, в общих чертах, описать функциональность, набросать вайрфреймы от руки. Дизайн-документ в граните не выбит, потом вполне себе может меняться, но как отправная точка имеет смысл.

**Comment by vitkarpov** [comment]
Когда определена базовая функциональность и есть вайрфремы, можно приступать к проектированию АПИ и базы данных — т.е. когда понятно какие реально действия с данными будут нужны.
